version: "3"

services:
  backend-core:
    env_file:
      - ./dev.env
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-core-v2.0
    restart: always
    volumes:
      - ./:/code/
    ports:
      - 5050:5050
