version: "3"

services:
  frontend:
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-v1.0
    depends_on:
      - backend-core
    restart: always
    ports:
      - 3000:3000

  backend-core:
    pull_policy: never
    env_file:
      - dev.env
    build:
      context: ally
      dockerfile: Dockerfile
    container_name: backend-core-v1.0
    volumes:
      - ./ally/:/code/
    command:
      - "hypercorn"
      - "main:app"
      - "--reload"
      - "--bind"
      - "0.0.0.0:5050"
    restart: always
    ports:
      - 5050:5050
