version: "3"

services:
  backend-core:
    env_file:
      - ./dev.env
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-core-v1.1
    restart: always
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
