version: "3"

services:
  frontend:
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-v2.0
    depends_on:
      - backend-core
    restart: always
    ports:
      - 443:443

  backend-core:
    pull_policy: never
    env_file:
      - dev.env
    build:
      context: ally
      dockerfile: Dockerfile
    container_name: backend-core-v2.0
    volumes:
      - ./ally/:/code/
    command:
      - "hypercorn"
      - "main:app"
      - "--reload"
      - "--bind"
      - "0.0.0.0:5050"
      - "--keyfile"
      - "/code/ssl/allyai.ai.key"
      - "--certfile"
      - "/code/ssl/allyai.ai.crt"
    restart: always
    ports:
      - 5050:5050
